#ifndef EDITEUR_HPP
#define EDITEUR_HPP

#include "general.hpp"


enum
{
	OBJET_INVALIDE=0,
	OBJET_BLOCTERRE1,
	OBJET_BLOCTERRE2,
	OBJET_BLOCTERRE3,
	OBJET_BLOCTERRE4,
	OBJET_BLOCTERRE5,
	OBJET_BLOCTERRE6,
	OBJET_BLOCTERRE7,
	OBJET_BLOCTERRE8,
	OBJET_BLOCTERRE9,
	OBJET_BLOCTERRE10,
	OBJET_BOITE_TOMBE,
	OBJET_SPAWN,
	OBJET_BOITE_CLEF1,
	OBJET_CLEF1,
	OBJET_BOITE_CLEF2,
	OBJET_CLEF2,
	OBJET_BOITE_CLEF3,
	OBJET_CLEF3,
	OBJET_BOITE_CLEF4,
	OBJET_CLEF4,
    OBJET_BOITE_CLEF5,
	OBJET_CLEF5,
    OBJET_BOITE_CLEF6,
	OBJET_CLEF6,
	OBJET_FLEUR,
	OBJET_BACON,
	OBJET_BAT,
    OBJET_OEUF,
	OBJET_SPAWN_DARKPOUSSIN_D,
	OBJET_FUSEE,
	OBJET_VENTILATEUR_DROITE,
    OBJET_VENTILATEUR_GAUCHE,
	OBJET_VENTILATEUR_HAUT,
	OBJET_LEVIER,
	OBJET_POTDEFLEUR
};


int choisir_objet(Position souris);
void ajouter_objet(Position souris, int objet);
void supprimer_objets(Position souris);


#endif
